### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by AhmedEwis** [momegas/megabots#24]
Hello,

I am following the code, but I am getting the below error in the first line of "from megabots import bot"

TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by AhmedEwis** [comment]
I am using Python 3.9.16 in my colab.

**Comment by momegas** [comment]
Can you try using 3.10 and up?

**Comment by momegas** [comment]
@AhmedEwis is this fixed with python 3.10?

**Comment by stavrostheocharis** [comment]
I had the same issue using python 3.8. It was fixed by using python 3.10.

**Comment by AhmedEwis** [comment]
@momegas yes, it is fixed, thank you!. I recommend to add this to the readme

**Comment by momegas** [comment]
Closing this then. Thank you for mentioning. I will
