### ISSUE TITLE
Integrate with langchain-serve?

### ISSUE THREAD

**Issue by deepankarm** [momegas/megabots#27]
**Is your feature request related to a problem? Please describe.**
Great work with megabots. Looks like a nice & easy API to develop LLM-based bots. What plans do you have to deploy the bots without adding infrastructure headache?

**Describe the solution you'd like**
I'd recommend integrating with [langchain-serve](https://github.com/jina-ai/langchain-serve). 

- Exposes APIs from function definitions locally as well as on the cloud.
- Very few lines of code changes, ease of development remains the same as local.
- Supports both REST & Websocket endpoints
- Serverless/autoscaling endpoints with automatic tls certs.
- Real-time streaming, human-in-the-loop support

**Comment by momegas** [comment]
This is the plan indeed. To create a super easy way to deploy an API. I was thinking FastAPI. There is already a function `create_api`. 

The module you propose seems to be Jina specific. This is why I went with FastAPI. I was thinking to also create a `fastapi_langchain` package to do exactly that. But ill need some more time 😅

I'll have a better look on the `langchain_serve` package, as well.

**Comment by deepankarm** [comment]
@momegas We use FastAPI to create the endpoints for both rest & websockets, and locally deploy them with uvicorn (like one would do) :slightly_smiling_face:.

Jina fills the gap from going from local to cloud with very few lines of code changes and with no infrastructure headache - and gets you the scalability.

**Comment by momegas** [comment]
Oh! That is great. Maybe then indeed it's what I need and can save some development time. Are you from the langchain-serve team? If so it would be nice to join our discord and discuss further integration 😁

**Comment by deepankarm** [comment]
Absolutely! Would you be able to [DM ](https://twitter.com/_deepankarm_) the discord link?

**Comment by Sassun** [comment]
+1 for megabots integration into langchain-serve :)
