### ISSUE TITLE
Error in langchain.embeddings load

### ISSUE THREAD

**Issue by stavrostheocharis** [momegas/megabots#28]
**Describe the bug**
When I run in the notebook the "qnabot = bot("qna-over-docs", "./index")" I get an error

Retrying langchain.embeddings.openai.embed_with_retry.<locals>._embed_with_retry in 4.0 seconds as it raised RateLimitError: You exceeded your current quota, please check your plan and billing details..

**Comment by momegas** [comment]
Can you have a look at your open AI account? I think thats where the problem is. It says you exceeded your quota so maybe you have placed a low threshold. Can you check?

**Comment by stavrostheocharis** [comment]
Ok, now I see, it needs a paid plan in openAI. Thanks.
